---@meta

---@alias definesEvents
---| "on_achievement_gained"
---| "on_ai_command_completed"
---| "on_area_cloned"
---| "on_biter_base_built"
---| "on_brush_cloned"
---| "on_build_base_arrived"
---| "on_built_entity"
---| "on_cancelled_deconstruction"
---| "on_cancelled_upgrade"
---| "on_character_corpse_expired"
---| "on_chart_tag_added"
---| "on_chart_tag_modified"
---| "on_chart_tag_removed"
---| "on_chunk_charted"
---| "on_chunk_deleted"
---| "on_chunk_generated"
---| "on_combat_robot_expired"
---| "on_console_chat"
---| "on_console_command"
---| "on_cutscene_cancelled"
---| "on_cutscene_finished"
---| "on_cutscene_started"
---| "on_cutscene_waypoint_reached"
---| "on_entity_cloned"
---| "on_entity_color_changed"
---| "on_entity_damaged"
---| "on_entity_died"
---| "on_entity_logistic_slot_changed"
---| "on_entity_renamed"
---| "on_entity_settings_pasted"
---| "on_entity_spawned"
---| "on_equipment_inserted"
---| "on_equipment_removed"
---| "on_force_cease_fire_changed"
---| "on_force_created"
---| "on_force_friends_changed"
---| "on_force_reset"
---| "on_forces_merged"
---| "on_forces_merging"
---| "on_game_created_from_scenario"
---| "on_gui_checked_state_changed"
---| "on_gui_click"
---| "on_gui_closed"
---| "on_gui_confirmed"
---| "on_gui_elem_changed"
---| "on_gui_hover"
---| "on_gui_leave"
---| "on_gui_location_changed"
---| "on_gui_opened"
---| "on_gui_selected_tab_changed"
---| "on_gui_selection_state_changed"
---| "on_gui_switch_state_changed"
---| "on_gui_text_changed"
---| "on_gui_value_changed"
---| "on_land_mine_armed"
---| "on_lua_shortcut"
---| "on_marked_for_deconstruction"
---| "on_marked_for_upgrade"
---| "on_market_item_purchased"
---| "on_mod_item_opened"
---| "on_object_destroyed"
---| "on_permission_group_added"
---| "on_permission_group_deleted"
---| "on_permission_group_edited"
---| "on_permission_string_imported"
---| "on_picked_up_item"
---| "on_player_alt_reverse_selected_area"
---| "on_player_alt_selected_area"
---| "on_player_ammo_inventory_changed"
---| "on_player_armor_inventory_changed"
---| "on_player_banned"
---| "on_player_built_tile"
---| "on_player_cancelled_crafting"
---| "on_player_changed_force"
---| "on_player_changed_position"
---| "on_player_changed_surface"
---| "on_player_cheat_mode_disabled"
---| "on_player_cheat_mode_enabled"
---| "on_player_clicked_gps_tag"
---| "on_player_configured_blueprint"
---| "on_player_controller_changed"
---| "on_player_crafted_item"
---| "on_player_created"
---| "on_player_cursor_stack_changed"
---| "on_player_deconstructed_area"
---| "on_player_demoted"
---| "on_player_died"
---| "on_player_display_density_scale_changed"
---| "on_player_display_resolution_changed"
---| "on_player_display_scale_changed"
---| "on_player_driving_changed_state"
---| "on_player_dropped_item"
---| "on_player_fast_transferred"
---| "on_player_flipped_entity"
---| "on_player_flushed_fluid"
---| "on_player_gun_inventory_changed"
---| "on_player_input_method_changed"
---| "on_player_joined_game"
---| "on_player_kicked"
---| "on_player_left_game"
---| "on_player_locale_changed"
---| "on_player_main_inventory_changed"
---| "on_player_mined_entity"
---| "on_player_mined_item"
---| "on_player_mined_tile"
---| "on_player_muted"
---| "on_player_pipette"
---| "on_player_placed_equipment"
---| "on_player_promoted"
---| "on_player_removed"
---| "on_player_removed_equipment"
---| "on_player_repaired_entity"
---| "on_player_respawned"
---| "on_player_reverse_selected_area"
---| "on_player_rotated_entity"
---| "on_player_selected_area"
---| "on_player_set_quick_bar_slot"
---| "on_player_setup_blueprint"
---| "on_player_toggled_alt_mode"
---| "on_player_toggled_map_editor"
---| "on_player_trash_inventory_changed"
---| "on_player_unbanned"
---| "on_player_unmuted"
---| "on_player_used_capsule"
---| "on_player_used_spidertron_remote"
---| "on_post_entity_died"
---| "on_pre_build"
---| "on_pre_chunk_deleted"
---| "on_pre_entity_settings_pasted"
---| "on_pre_ghost_deconstructed"
---| "on_pre_ghost_upgraded"
---| "on_pre_permission_group_deleted"
---| "on_pre_permission_string_imported"
---| "on_pre_player_crafted_item"
---| "on_pre_player_died"
---| "on_pre_player_left_game"
---| "on_pre_player_mined_item"
---| "on_pre_player_removed"
---| "on_pre_player_toggled_map_editor"
---| "on_pre_robot_exploded_cliff"
---| "on_pre_scenario_finished"
---| "on_pre_script_inventory_resized"
---| "on_pre_surface_cleared"
---| "on_pre_surface_deleted"
---| "on_redo_applied"
---| "on_research_cancelled"
---| "on_research_finished"
---| "on_research_moved"
---| "on_research_reversed"
---| "on_research_started"
---| "on_resource_depleted"
---| "on_robot_built_entity"
---| "on_robot_built_tile"
---| "on_robot_exploded_cliff"
---| "on_robot_mined"
---| "on_robot_mined_entity"
---| "on_robot_mined_tile"
---| "on_robot_pre_mined"
---| "on_rocket_launch_ordered"
---| "on_rocket_launched"
---| "on_runtime_mod_setting_changed"
---| "on_script_inventory_resized"
---| "on_script_path_request_finished"
---| "on_script_trigger_effect"
---| "on_sector_scanned"
---| "on_segment_entity_created"
---| "on_selected_entity_changed"
---| "on_space_platform_built_entity"
---| "on_space_platform_built_tile"
---| "on_space_platform_changed_state"
---| "on_space_platform_mined_entity"
---| "on_space_platform_mined_item"
---| "on_space_platform_mined_tile"
---| "on_space_platform_pre_mined"
---| "on_spider_command_completed"
---| "on_string_translated"
---| "on_surface_cleared"
---| "on_surface_created"
---| "on_surface_deleted"
---| "on_surface_imported"
---| "on_surface_renamed"
---| "on_technology_effects_reset"
---| "on_tick"
---| "on_train_changed_state"
---| "on_train_created"
---| "on_train_schedule_changed"
---| "on_trigger_created_entity"
---| "on_trigger_fired_artillery"
---| "on_undo_applied"
---| "on_unit_added_to_group"
---| "on_unit_group_created"
---| "on_unit_group_finished_gathering"
---| "on_unit_removed_from_group"
---| "on_worker_robot_expired"
---| "script_raised_built"
---| "script_raised_destroy"
---| "script_raised_revive"
---| "script_raised_set_tiles"
---| "script_raised_teleported"

---@alias definesInventory
---| "fuel"
---| "burnt_result"
---| "chest"
---| "logistic_container_trash"
---| "furnace_source"
---| "furnace_result"
---| "furnace_modules"
---| "character_main"
---| "character_guns"
---| "character_ammo"
---| "character_armor"
---| "character_vehicle"
---| "character_trash"
---| "god_main"
---| "editor_main"
---| "editor_guns"
---| "editor_ammo"
---| "editor_armor"
---| "roboport_robot"
---| "roboport_material"
---| "robot_cargo"
---| "robot_repair"
---| "assembling_machine_input"
---| "assembling_machine_output"
---| "assembling_machine_modules"
---| "assembling_machine_dump"
---| "lab_input"
---| "lab_modules"
---| "mining_drill_modules"
---| "item_main"
---| "rocket_silo_rocket"
---| "rocket_silo_trash"
---| "rocket_silo_input"
---| "rocket_silo_output"
---| "rocket_silo_modules"
---| "cargo_unit"
---| "car_trunk"
---| "car_ammo"
---| "cargo_wagon"
---| "turret_ammo"
---| "beacon_modules"
---| "character_corpse"
---| "artillery_turret_ammo"
---| "artillery_wagon_ammo"
---| "spider_trunk"
---| "spider_ammo"
---| "spider_trash"
---| "hub_main"
---| "hub_trash"
---| "cargo_landing_pad_main"
---| "cargo_landing_pad_trash"

---@class (exact) defines
---@field alert_type table
---@field behavior_result table
---@field build_check_type table
---@field build_mode table
---@field chain_signal_state table
---@field chunk_generated_status table
---@field command table
---@field compound_command table
---@field control_behavior table
---@field controllers table
---@field deconstruction_item table
---@field default_icon_size table
---@field difficulty table
---@field direction table
---@field disconnect_reason table
---@field distraction table
---@field entity_status table
---@field entity_status_diode table
---@field events definesEvents
---@field flow_precision_index table
---@field game_controller_interaction table
---@field group_state table
---@field gui_type table
---@field input_action table
---@field input_method table
---@field inventory definesInventory
---@field logistic_member_index table
---@field logistic_mode table
---@field logistic_section_type table
---@field mouse_button_type table
---@field moving_state table
---@field print_skip table
---@field print_sound table
---@field prototypes table
---@field rail_connection_direction table
---@field rail_direction table
---@field rail_layer table
---@field relative_gui_position table
---@field relative_gui_type table
---@field render_mode table
---@field rich_text_setting table
---@field riding table
---@field robot_order_type table
---@field rocket_silo_status table
---@field selection_mode table
---@field shooting table
---@field signal_state table
---@field space_platform_state table
---@field target_type table
---@field train_state table
---@field transport_line table
---@field wire_connector_id table
---@field wire_origin table
---@field wire_type table

defines = {}


---@class game
---@field players table
---@field set_game_state function
game = {}

---@alias TargetType
---| "entity"
---| "position"
---| "direction"

---@class AmmoType
---@field target_type TargetType

---@class itemPrototype
---@field stack_size? number
---@field fuel_category? string
---@field fuel_value? number
---@field get_ammo_type? function
---@field order? string

itemPrototype = {}

---@return AmmoType
function itemPrototype.get_ammo_type() end

---@class prototypes
---@field item table<string, itemPrototype>
prototypes = {}

---@class script
script = {}

---@param fn function
function script.on_init(fn) end

---@param fn function
function script.on_load(fn) end

---@param fn function
function script.on_configuration_changed(fn) end

---@param event string
---@param fn function
function script.on_event(event, fn) end
